### PR TITLE
Move to vscode-languageclient 8.0.2

### PR DESCRIPTION
**Pull request by JessicaJHee**
Signed-off-by: Jessica He <jhe@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
There is a compilation error in one of the test files (you can see it if you run `npm test`).

**Comment by datho7561** [comment]
(sorry, didn't realize you already had a PR for this)

**Comment by JessicaJHee** [comment]
> (sorry, didn't realize you already had a PR for this)

No that's my bad, I should have created an issue for it first or included it in my stand up

**Review by datho7561 — APPROVED** [review]
Looks good. Thanks, Jessica!

**Comment by datho7561** [comment]
Closes #145

**Pull request merged**
