### PR TITLE
Expose the 'microprofile.tools.validation.expression.excluded' settings.

### PR DESCRIPTION
**Pull request by angelozerr**
Expose the 'microprofile.tools.validation.expression.excluded' settings.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Review by AlexXuChen — COMMENTED** [review]
By changing the package.json, maybe run an `npm install` before merging?

**Review by AlexXuChen — COMMENTED** [review]
I believe the setting isn't working as intended. For example, if I have an application properties file as follows:
```
%prod.quarkus.datasource.username = ${DBUSER:sa}
```
where `DBUSER:sa` throws an error, none of the following expressions added the the setting will resolve the error:
Screenshot from 2021-09-09 09-28-45
However, adding `*` will always work for any expression value, as expected.

**Comment by fbricon** [comment]
@AlexXuChen in `${DBUSER:sa}`, `sa` is the default value. So the property name is actually `DBUSER`

**Comment by AlexXuChen** [comment]
> @AlexXuChen in `${DBUSER:sa}`, `sa` is the default value. So the property name is actually `DBUSER`

So if I add `DBUSER` to the setting, should the expected behaviour be that it is ignored?  Currently that is one of the items in the list I was testing.

**Comment by fbricon** [comment]
if you add DBUSER=alex to the properties, then there should be no warnings/errors

**Comment by angelozerr** [comment]
@AlexXuChen please read my comments at https://github.com/redhat-developer/vscode-quarkus/issues/392#issuecomment-915878138 The exclusion is done for a given property name, not for the value.

**Comment by AlexXuChen** [comment]
> @AlexXuChen please read my comments at [redhat-developer/vscode-quarkus#392 (comment)](https://github.com/redhat-developer/vscode-quarkus/issues/392#issuecomment-915878138) The exclusion is done for a given property name, not for the value.

Ah okay, yes I see that working now

**Comment by AlexXuChen** [comment]
> if you add DBUSER=alex to the properties, then there should be no warnings/errors

This however I couldn't get to work

**Comment by angelozerr** [comment]
It should work, it was implemented since a long time. Which settings are you using?

**Comment by AlexXuChen** [comment]
> It should work, it was implemented since a long time. Which settings are you using?

microprofile.tools.validation.expression.excluded

**Comment by AlexXuChen** [comment]
But the setting is for the array of properties, not the value as you said, so adding `quarkus.datasource.username` will work.

**Comment by angelozerr** [comment]
Ok, perfect. So it work.

**Review by AlexXuChen — APPROVED** [review]
LGTM

**Pull request merged**
